version: "3.9"
services:
  client:
    build:
      context: ./myapp
    ports:
      - "3000:3000"
    volumes:
      - ./myapp:/myapp
    image: shivanitijare/client:client
    container_name: react_container
    command: npm start

  mssql:
    image: shivanitijare/get_certified_online_mssql
    build: ./Get_Certified_Online_db
    container_name: db
    ports:
      - "1433:1433"
 
  api:
    image: shivanitijare/api
    build:
      context: ./Get_Certified_Online_api
      dockerfile: ./Get_Certified_Online_api/Dockerfile
    ports:
      - "5000:443"
      - "5001:80"
    environment:
      ASPNETCORE_URLS: "http://+80;https://+443"
      ASPNETCORE_HTTPS_PORT: "5000"
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: 'true'
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ./Get_Certified_Online_api/Get_Certified_Online_api:/Get_Certified_Online_api
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https
      - ${APPDATA}/Microsoft/UseSecrets:/root/.microsoft/usersecrets
      - ~/.aspnet/https:/https
    container_name: api
    depends_on:
      - mssql
  